Add support for removing a menu item
fyne-io/systray pull request #34
Opened 2022-12-19 22:06 UTC by bdwyertech

Resolves #33

2022-12-20 20:42 UTC, andydotxyz requested changes
Nice addition, thanks.
I think some code is needed for unix as well?

2022-12-20 20:42 UTC, andydotxyz commented on systray_darwin.m
> +  NSMenuItem* menuItem = find_menu_item(menu, menuId);
This line, and the one 2 lines lower, seem to have bad indent

2022-12-21 03:56 UTC, bdwyertech commented
> Nice addition, thanks. I think some code is needed for unix as well?

I'll have to give the Unix code a further look.  Quick glance says pruning the button ID from a slice and triggering a refresh.

Also, I did notice another memory leak I cannot quite figure out... Seems to be related to the Icon setting code on Darwin specifically.  If I use a test harness to delete/create a new MenuItem every few seconds, after a few hours the memory usage multiplies exponentially.  pprof nor Datadog show anything.  If I remove SetIcon from the loop, the memory does not balloon nearly as badly.  My thought is something is not freeing up no longer used resources, probably something in the cast from CGO -> NSData -> NSImage -> NSMenuItem.image.

2022-12-21 09:41 UTC, andydotxyz commented
Thanks, do post here if you need more assistance with the unix code.

With regards to icon memory leak, I think that also was reported in our usage in the toolkit at https://github.com/fyne-io/fyne/issues/3463, so you're not the only one to see it. The image data is obviously not being cleaned up in the C code.

2022-12-21 19:53 UTC, bdwyertech commented
> Thanks, do post here if you need more assistance with the unix code.
> 
> With regards to icon memory leak, I think that also was reported in our usage in the toolkit at [fyne-io/fyne#3463](https://github.com/fyne-io/fyne/issues/3463), so you're not the only one to see it. The image data is obviously not being cleaned up in the C code.

Should all be resolved now.  Tested the tray on Kali, that dbus system is pretty interesting!

2023-01-16 17:52 UTC, andydotxyz approved these changes
Nice one thanks!

2023-01-16 17:52 UTC, merged